dist: trusty
group: travis_latest
sudo: false
cache:
  directories:
    - $HOME/.cache/pip

language: python


matrix:
  fast_finish: true

  include:
    - python: "2.7"
      env: TOXENV=py27-threads
    - python: "3.4"
      env: TOXENV=py34-threads
    - python: "3.5"
      env: TOXENV=py35-threads
    - python: "3.6"
      env: TOXENV=py36-threads
    - python: "3.7"
      env: TOXENV=py37-threads
    - python: "pypy"
      env: TOXENV=pypy-threads
    - python: "pypy"
      env: TOXENV=pypy3-threads
    - python: "2.7"
      env: TOXENV=py27-greenlets
    - python: "2.7"
      env: TOXENV=py27-colorama
    - python: "2.7"
      env: TOXENV=py27-oldtwisted
    - python: "3.7"
      env: TOXENV=py37-greenlets
    - python: "3.7"
      env: TOXENV=py37-colorama
    - python: "3.7"
      env: TOXENV=py37-oldtwisted
    - python: "pypy"
      env: TOXENV=pypy-greenlets
    - python: "pypy"
      env: TOXENV=pypy-colorama
    - python: "pypy"
      env: TOXENV=pypy-oldtwisted

    # Prevent breakage by a new releases
    - python: "3.6-dev"
      env: TOXENV=py36-threads
    - python: "3.6-dev"
      env: TOXENV=py36-greenlets
    - python: "3.7-dev"
      env: TOXENV=py37-threads
    - python: "3.7-dev"
      env: TOXENV=py37-greenlets

    # Meta
    - python: "3.6"
      env: TOXENV=lint
    - python: "3.6"
      env: TOXENV=manifest
    - python: "3.6"
      env: TOXENV=docs
    - python: "3.6"
      env: TOXENV=readme

  allow_failures:
    - python: "3.6-dev"
    - python: "3.7-dev"


install:
  - pip install tox


script:
  - tox


before_install:
  - pip install codecov


after_success:
  - tox -e coverage-report
  - codecov


notifications:
  email: false
