dist: xenial
group: travis_latest
sudo: false
cache:
  directories:
    - $HOME/.cache/pip

language: python


matrix:
  fast_finish: true

  include:
    # lint
    - python: "3.7"
      stage: lint
      env: TOXENV=lint
    - python: "3.7"
      env: TOXENV=manifest

    # test
    - python: "2.7"
      stage: test
      env: TOXENV=py27-threads
    - python: "3.4"
      env: TOXENV=py34-threads
    - python: "3.5"
      env: TOXENV=py35-threads
    - python: "3.6"
      env: TOXENV=py36-threads
    - python: "3.7"
      env: TOXENV=py37-threads
    - python: "pypy"
      env: TOXENV=pypy-threads
      dist: trusty
    - python: "pypy3"
      env: TOXENV=pypy3-threads
      dist: trusty
    - python: "2.7"
      env: TOXENV=py27-greenlets
    - python: "2.7"
      env: TOXENV=py27-colorama
    - python: "2.7"
      env: TOXENV=py27-oldtwisted
    - python: "3.7"
      env: TOXENV=py37-greenlets
      dist: xenial
      sudo: true
    - python: "3.7"
      env: TOXENV=py37-colorama
      dist: xenial
      sudo: true
    - python: "3.7"
      env: TOXENV=py37-oldtwisted
      dist: xenial
      sudo: true
    - python: "pypy"
      env: TOXENV=pypy-greenlets
      dist: trusty
    - python: "pypy"
      env: TOXENV=pypy-colorama
      dist: trusty
    - python: "pypy"
      env: TOXENV=pypy-oldtwisted
      dist: trusty

    # Prevent breakage by a new releases
    - python: "3.7-dev"
      env: TOXENV=py37-threads
    - python: "3.7-dev"
      env: TOXENV=py37-greenlets

    # docs
    - python: "3.7"
      stage: docs
      env: TOXENV=docs
    - python: "3.7"
      env: TOXENV=pypi-description

  allow_failures:
    - python: "3.7-dev"


install:
  - pip install tox


script:
  - tox


before_install:
  - pip install codecov


after_success:
  - tox -e coverage-report
  - codecov


notifications:
  email: false
