sudo: false
cache:
  directories:
    - $HOME/.cache/pip

language: python


matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27-threads
    - python: "2.7"
      env: TOXENV=py27-greenlets
    - python: "3.4"
      env: TOXENV=py34-threads
    - python: "3.4"
      env: TOXENV=py34-greenlets
    - python: "3.5"
      env: TOXENV=py35-threads
    - python: "3.5"
      env: TOXENV=py35-greenlets
    - python: "3.5"
      env: TOXENV=py35-nocolorama
    - python: "pypy"
      env: TOXENV=pypy-threads
    - python: "pypy"
      env: TOXENV=pypy-greenlets


    # Meta
    - python: "3.5"
      env: TOXENV=flake8
    - python: "3.5"
      env: TOXENV=manifest
    - python: "3.5"
      env: TOXENV=docs
    - python: "3.5"
      env: TOXENV=readme


install:
  - pip install tox


script:
  - tox


before_install:
  - pip install codecov


after_success:
  - tox -e coverage-report
  - codecov


notifications:
  email: false
